//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLetsTatoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mLetsTatoo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is blocked, please contact the technical support at soporte@letstattoo.com.mx.
        /// </summary>
        internal static string AccountBloqued {
            get {
                return ResourceManager.GetString("AccountBloqued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least 18 years old..
        /// </summary>
        internal static string AgeError {
            get {
                return ResourceManager.GetString("AgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate....
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your Birthdate..
        /// </summary>
        internal static string BirthdateError {
            get {
                return ResourceManager.GetString("BirthdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password in Confirm Password field as in the Password field.
        /// </summary>
        internal static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid Email..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered has already been registered previously, please register another one..
        /// </summary>
        internal static string EmailExistError {
            get {
                return ResourceManager.GetString("EmailExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number....
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on internet settings or disable Airplane Mode on your device..
        /// </summary>
        internal static string ErrorConfigInternet {
            get {
                return ResourceManager.GetString("ErrorConfigInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection!.
        /// </summary>
        internal static string ErrorInternet {
            get {
                return ResourceManager.GetString("ErrorInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not allowed for this platform..
        /// </summary>
        internal static string ErrorTypeUser {
            get {
                return ResourceManager.GetString("ErrorTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong User or Password.
        /// </summary>
        internal static string ErrorUsuarioyPassword {
            get {
                return ResourceManager.GetString("ErrorUsuarioyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From gallery.
        /// </summary>
        internal static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password !.
        /// </summary>
        internal static string IntroducirPasword {
            get {
                return ResourceManager.GetString("IntroducirPasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your user.
        /// </summary>
        internal static string IntroducirUsuario {
            get {
                return ResourceManager.GetString("IntroducirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your lastname..
        /// </summary>
        internal static string LastnameError {
            get {
                return ResourceManager.GetString("LastnameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and the Confirm Password fields is no match, you must enter the same password on both fields..
        /// </summary>
        internal static string MatchPasswordError {
            get {
                return ResourceManager.GetString("MatchPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your name..
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a new picture.
        /// </summary>
        internal static string NewPicture {
            get {
                return ResourceManager.GetString("NewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string OlvidoPassword {
            get {
                return ResourceManager.GetString("OlvidoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Password..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your personal data....
        /// </summary>
        internal static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your phone number..
        /// </summary>
        internal static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this device!.
        /// </summary>
        internal static string Recordarme {
            get {
                return ResourceManager.GetString("Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account data.
        /// </summary>
        internal static string RegAccount {
            get {
                return ResourceManager.GetString("RegAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string RegPersonal {
            get {
                return ResourceManager.GetString("RegPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your account data....
        /// </summary>
        internal static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Username..
        /// </summary>
        internal static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you entered already exists, you must enter another one..
        /// </summary>
        internal static string UserExistError {
            get {
                return ResourceManager.GetString("UserExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the picture?.
        /// </summary>
        internal static string WhereTakePicture {
            get {
                return ResourceManager.GetString("WhereTakePicture", resourceCulture);
            }
        }
    }
}
