//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLetsTatoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mLetsTatoo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string AboutStudie {
            get {
                return ResourceManager.GetString("AboutStudie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is blocked, please contact the technical support at soporte@letstattoo.com.mx.
        /// </summary>
        internal static string AccountBloqued {
            get {
                return ResourceManager.GetString("AccountBloqued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code.
        /// </summary>
        internal static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the correct activation code..
        /// </summary>
        internal static string ActivationCodeError {
            get {
                return ResourceManager.GetString("ActivationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an image of the art you want ....
        /// </summary>
        internal static string AddArtImage {
            get {
                return ResourceManager.GetString("AddArtImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill all the advance fields ....
        /// </summary>
        internal static string AdvanceError {
            get {
                return ResourceManager.GetString("AdvanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least 18 years old..
        /// </summary>
        internal static string AgeError {
            get {
                return ResourceManager.GetString("AgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The advance for your appointment is:.
        /// </summary>
        internal static string AppointmentCost {
            get {
                return ResourceManager.GetString("AppointmentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule your appointment!.
        /// </summary>
        internal static string AppointmentSchedule {
            get {
                return ResourceManager.GetString("AppointmentSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do you want the appointment?.
        /// </summary>
        internal static string AppointmentWhen {
            get {
                return ResourceManager.GetString("AppointmentWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want the appointment with?.
        /// </summary>
        internal static string AppointmentWho {
            get {
                return ResourceManager.GetString("AppointmentWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The approximate total cost of your art is:.
        /// </summary>
        internal static string ApproximateCost {
            get {
                return ResourceManager.GetString("ApproximateCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big.
        /// </summary>
        internal static string Big {
            get {
                return ResourceManager.GetString("Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate....
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your Birthdate..
        /// </summary>
        internal static string BirthdateError {
            get {
                return ResourceManager.GetString("BirthdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Office.
        /// </summary>
        internal static string BranchOffice {
            get {
                return ResourceManager.GetString("BranchOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch offices.
        /// </summary>
        internal static string BranchOffices {
            get {
                return ResourceManager.GetString("BranchOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Personal Information.
        /// </summary>
        internal static string ChangePersonal {
            get {
                return ResourceManager.GetString("ChangePersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, it is necessary that you fill out the form with the pre-established Features for the art that the clients will select..
        /// </summary>
        internal static string CompleteFeatures {
            get {
                return ResourceManager.GetString("CompleteFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity:.
        /// </summary>
        internal static string Complexity {
            get {
                return ResourceManager.GetString("Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password in Confirm Password field as in the Password field.
        /// </summary>
        internal static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill out all the cost fields ....
        /// </summary>
        internal static string CostError {
            get {
                return ResourceManager.GetString("CostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password that you entered, must be the same as your current password.
        /// </summary>
        internal static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date can not be earlier than today!.
        /// </summary>
        internal static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your art....
        /// </summary>
        internal static string DescribeArt {
            get {
                return ResourceManager.GetString("DescribeArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a description of the art you want!.
        /// </summary>
        internal static string DescribeArtError {
            get {
                return ResourceManager.GetString("DescribeArtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid Email..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered has already been registered previously, please register another one..
        /// </summary>
        internal static string EmailExistError {
            get {
                return ResourceManager.GetString("EmailExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number....
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on internet settings or disable Airplane Mode on your device..
        /// </summary>
        internal static string ErrorConfigInternet {
            get {
                return ResourceManager.GetString("ErrorConfigInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection!.
        /// </summary>
        internal static string ErrorInternet {
            get {
                return ResourceManager.GetString("ErrorInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not allowed for this platform..
        /// </summary>
        internal static string ErrorTypeUser {
            get {
                return ResourceManager.GetString("ErrorTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong User or Password.
        /// </summary>
        internal static string ErrorUsuarioyPassword {
            get {
                return ResourceManager.GetString("ErrorUsuarioyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated duration time:.
        /// </summary>
        internal static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add all the example images ....
        /// </summary>
        internal static string ExampleImageError {
            get {
                return ResourceManager.GetString("ExampleImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features of your art....
        /// </summary>
        internal static string FeaturesArt {
            get {
                return ResourceManager.GetString("FeaturesArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all the features.
        /// </summary>
        internal static string FillFeatures {
            get {
                return ResourceManager.GetString("FillFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From gallery.
        /// </summary>
        internal static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce your activation code!.
        /// </summary>
        internal static string IntroduceActivationCode {
            get {
                return ResourceManager.GetString("IntroduceActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password !.
        /// </summary>
        internal static string IntroducirPasword {
            get {
                return ResourceManager.GetString("IntroducirPasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your user.
        /// </summary>
        internal static string IntroducirUsuario {
            get {
                return ResourceManager.GetString("IntroducirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your lastname..
        /// </summary>
        internal static string LastnameError {
            get {
                return ResourceManager.GetString("LastnameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and the Confirm Password fields is no match, you must enter the same password on both fields..
        /// </summary>
        internal static string MatchPasswordError {
            get {
                return ResourceManager.GetString("MatchPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum measure selected for your art is:.
        /// </summary>
        internal static string MaximunSize {
            get {
                return ResourceManager.GetString("MaximunSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumComplexity {
            get {
                return ResourceManager.GetString("MediumComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumSize {
            get {
                return ResourceManager.GetString("MediumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your name..
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t introduce negative values!.
        /// </summary>
        internal static string NegativeError {
            get {
                return ResourceManager.GetString("NegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be different as current password.
        /// </summary>
        internal static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a new picture.
        /// </summary>
        internal static string NewPicture {
            get {
                return ResourceManager.GetString("NewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your current password.
        /// </summary>
        internal static string NoCurrentPassword {
            get {
                return ResourceManager.GetString("NoCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice!.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string OlvidoPassword {
            get {
                return ResourceManager.GetString("OlvidoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Password..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your personal data....
        /// </summary>
        internal static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your phone number..
        /// </summary>
        internal static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this device!.
        /// </summary>
        internal static string Recordarme {
            get {
                return ResourceManager.GetString("Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account data.
        /// </summary>
        internal static string RegAccount {
            get {
                return ResourceManager.GetString("RegAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string RegPersonal {
            get {
                return ResourceManager.GetString("RegPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search appointments....
        /// </summary>
        internal static string SearchAppointment {
            get {
                return ResourceManager.GetString("SearchAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search artists....
        /// </summary>
        internal static string SearchArtists {
            get {
                return ResourceManager.GetString("SearchArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search studios....
        /// </summary>
        internal static string SearchStudios {
            get {
                return ResourceManager.GetString("SearchStudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artist....
        /// </summary>
        internal static string SelectArtist {
            get {
                return ResourceManager.GetString("SelectArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select the artist you want to make your art!.
        /// </summary>
        internal static string SelectedArtistError {
            get {
                return ResourceManager.GetString("SelectedArtistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the estimated time duration for this feature..
        /// </summary>
        internal static string SelectEstimatedTime {
            get {
                return ResourceManager.GetString("SelectEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the size values ​​to continue!.
        /// </summary>
        internal static string SizeError {
            get {
                return ResourceManager.GetString("SizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        internal static string Study {
            get {
                return ResourceManager.GetString("Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your account data....
        /// </summary>
        internal static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Username..
        /// </summary>
        internal static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you entered already exists, you must enter another one..
        /// </summary>
        internal static string UserExistError {
            get {
                return ResourceManager.GetString("UserExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the picture?.
        /// </summary>
        internal static string WhereTakePicture {
            get {
                return ResourceManager.GetString("WhereTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
