//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLetsTatoo.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mLetsTatoo.Resourses.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enciende las configuraciones de internet o deshabilita el Modo Avión de tu dispositivo..
        /// </summary>
        public static string ErrorConfigInternet {
            get {
                return ResourceManager.GetString("ErrorConfigInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica tu conexión a internet..
        /// </summary>
        public static string ErrorInternet {
            get {
                return ResourceManager.GetString("ErrorInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Usuario o contraseña incorrectos!.
        /// </summary>
        public static string ErrorUsuarioyPassword {
            get {
                return ResourceManager.GetString("ErrorUsuarioyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Debes introducir su contraseña!.
        /// </summary>
        public static string IntroducirPasword {
            get {
                return ResourceManager.GetString("IntroducirPasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Debe introducir su usuario!.
        /// </summary>
        public static string IntroducirUsuario {
            get {
                return ResourceManager.GetString("IntroducirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string OlvidoPassword {
            get {
                return ResourceManager.GetString("OlvidoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme en este dispositiv.
        /// </summary>
        public static string Recordarme {
            get {
                return ResourceManager.GetString("Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        public static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
